Ectoplasm chance
GTNewHorizons/Hardcore-Ender-Expansion pull request #5
Opened 2021-07-24 17:59 UTC by Sphyix

Changed the ectoplasm chance to actually match Ender Compendium explanation on the drop rate
![javaw_qU7eW990pt](https://user-images.githubusercontent.com/17811922/126877239-a60a8ad7-154a-470d-aaee-bfd43b278c34.png)

I looked at the code and saw the differences while trying to do the quests to unlock draconic evolution and getting really frustrated on the drop rate of ectoplasm from the spooky trees

2021-07-24 18:30 UTC, yukieiji commented
I don't think it's necessary because the HEE quest reward is some Ectoplasm.

2021-07-24 18:55 UTC, Sphyix commented
I don't think that having enough on the quests can justify a really low drop rate compared to what it should be

2021-07-24 19:15 UTC, yukieiji commented
I told Dream about it, later HEE quests are implemented.
So maybe we should make a ticket to discuss the quest changes and other issues before we issue a PR to fix the drop rate
![キャプチャ91](https://user-images.githubusercontent.com/40425798/126879036-01ad8963-c12c-4fa9-ab5c-2fe62f2c78d8.PNG)

2021-07-24 19:20 UTC, Sphyix commented
I'll leave this here and make a ticket, btw I don't see a coins quest for ectoplasm and I don't see the reason for the droprate to be so low.. are players just forced to follow quests to get it?

2021-07-24 19:32 UTC, boubou19 commented
Thing is there is definitely something wrong because the wiki from the mod itself is saying we should have a 60% chance of getting it, but it's actually set to 5%. And it was an issue in the base mod, because no one changed this class except the original mod author. So yeah we can talk about the balance, but at least we must be consistant between what the in game wiki says and what it really is.

2021-07-24 21:32 UTC, Dream-Master commented
60% is to much 5% to low. maybe 25% fit

2021-07-26 08:01 UTC, boubou19 requested changes
every lang file entry must be written on a single line

2021-07-26 08:46 UTC, boubou19 approved these changes

2021-07-26 18:23 UTC, merged